### ISSUE TITLE
User get unadded vaccine

### ISSUE THREAD

**Issue by tiemfah** [chiiida/vacseen#15]
video: [Google Drive](https://drive.google.com/open?id=1Lugx8FLVniRF1pU-ivneSaYw0Dp3Rn-r)

**Comment by chiiida** [comment]
It is suggested vaccine which is now testing with only age since we still don't have enough vaccine model in database. User will get unadded vaccines but won't track those vaccines until user input the first date that the user will receive the first dose of that vaccine.

**Comment by chiiida** [comment]
It is also in progress. So, it does not finish yet.
