### ISSUE TITLE
Add gender field to Vaccine model.

### ISSUE THREAD

**Issue by tiemfah** [chiiida/vacseen#5]
https://github.com/llleyelll/vacseen/blob/0a11f6f8938af371fb9a6dd326fd9d72af3aa000/vaccine/models.py#L4-L14

Class Vaccine would need a gender field to be use to recommend to users.
 - [x] add gender field

**Comment by tiemfah** [comment]
@llleyelll

**Comment by chiiida** [comment]
I added gender to the Vaccine model.
Please check it 👍
